### ISSUE TITLE
Remove PeerGone action

### ISSUE THREAD

**Issue by tebben** [Geodan/cow#183]
Send an UpdateRecord action with deleted parameter to true for a peer on disconnect instead of a PeerGone action.

**Comment by tomvantilburg** [comment]
This is not recommended since CASH has no knowledge of any other data attached to the peer while the updatedRecord method requires a full record object. Also, it is up to the clients to decide what to do with a peerGone action, they might not want to give it a deleted status.
Therefore leaving as it is.
